version: "3.8"

services:
  campaign-service:
    build: .
    image: sandeepkrjsr/campaign-service:v1.0.${BUILD_NUMBER}
    container_name: campaign-service
    ports:
      - "8080:8080"
    restart: always