services:
  campaign-service:
    build: .
    image: campaign-service:v1.0.${BUILD_NUMBER}
    container_name: campaign-service-v1.0.${BUILD_NUMBER}
    ports:
      - "8080:8080"
    restart: always